/** Pino redact paths — secrets never appear in CloudWatch / log forwarders. */
export const LOG_REDACT_PATHS = [
  "authorization",
  "req.headers.authorization",
  "headers.authorization",
  // AUTH-BE-14 — the refresh-token cookie must never be logged, same reasoning as the
  // Authorization header above (it is the raw, pre-hash credential).
  "cookie",
  "req.headers.cookie",
  "headers.cookie",
  "set-cookie",
  "req.headers['set-cookie']",
  "headers['set-cookie']",
  "*.password",
  "*.refreshCookie",
  "*.secret",
  "*.apiKey",
  "*.api_key",
  "*.token",
  "*.otp",
  "*.code",
  "*.inviteToken",
  "*.sessionToken",
  "*.codeVerifier",
  "*.code_verifier",
  "*.idToken",
  "*.id_token",
  "*.accessToken",
  "*.refreshToken",
  "*.clientSecret",
  "*.encryptionKey",
  "INTEGRATION_ENCRYPTION_KEY",
  "HUBSPOT_CLIENT_SECRET",
  "GOOGLE_OAUTH_CLIENT_SECRET",
  "CLERK_SECRET_KEY",
  "OPENAI_API_KEY",
  "DATABASE_PASSWORD",
  "DATABASE_URL",
] as const;
