#!/usr/bin/env tsx
/**
 * Generates .env.local files for backend and frontend from local CDK config.
 * Run: pnpm --filter @skout/infra local:env
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { ENVIRONMENTS } from "../lib/config/environments.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const backendRoot = resolve(__dirname, "../..");
const frontendRoot = resolve(backendRoot, "../Skout Ai Frontend");

const local = ENVIRONMENTS.local;

const backendEnv = `# Generated by infra/scripts/generate-local-env.ts — do not commit secrets
NODE_ENV=development
PORT=3001
HOST=0.0.0.0
LOG_LEVEL=debug

DATABASE_URL=postgresql://skout:skout@localhost:5432/skout
REDIS_URL=redis://localhost:6379
CORS_ORIGIN=http://localhost:3000

OPENSEARCH_URL=http://localhost:9200
AI_SERVICE_URL=http://localhost:8000

# Optional — set in shell or .env
# OPENAI_API_KEY=
# CLERK_SECRET_KEY=
`;

const frontendEnv = `# Generated by infra/scripts/generate-local-env.ts
NEXT_PUBLIC_API_URL=http://localhost:3001

# Optional — Clerk (when auth is wired)
# NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
`;

writeFileSync(resolve(backendRoot, ".env.local.generated"), backendEnv);
mkdirSync(frontendRoot, { recursive: true });
writeFileSync(resolve(frontendRoot, ".env.local.generated"), frontendEnv);

console.log("✓ Wrote .env.local.generated (backend)");
console.log("✓ Wrote ../Skout Ai Frontend/.env.local.generated");
console.log("\nBackend stack:");
console.log("  docker compose -f docker-compose.yml -f docker-compose.local.yml up --build");
console.log("\nFrontend (separate repo — Skout Ai Frontend):");
console.log("  docker compose -f docker-compose.yml -f docker-compose.local.yml up --build");
console.log(`\nEnvironment: ${local.name} | region: ${local.region}`);
