-- COPS-04: credit ledger made append-only and attributable; trial provisioning saga.
-- Idempotent: safe to run twice.

-- 1. Ledger columns on the existing credit_transactions table.
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "seq" bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "kind" text;
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "category" text;
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "balance_after" integer;
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "reason" text;
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "actor_type" text;
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "actor_id" text;
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "idempotency_key" text;
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "correlation_id" text;
ALTER TABLE "credit_transactions" ADD COLUMN IF NOT EXISTS "compensates_id" uuid;
DO $$ BEGIN
  ALTER TABLE "credit_transactions" ADD CONSTRAINT "credit_transactions_compensates_id_fk"
    FOREIGN KEY ("compensates_id") REFERENCES "credit_transactions"("id");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE UNIQUE INDEX IF NOT EXISTS "credit_transactions_idempotency_uq"
  ON "credit_transactions" ("workspace_id", "idempotency_key") WHERE "idempotency_key" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "credit_transactions_workspace_seq_idx" ON "credit_transactions" ("workspace_id", "seq");

-- 2. Backfill kind for rows written before COPS-04 (before the append-only trigger exists).
UPDATE "credit_transactions" SET "kind" = CASE
    WHEN "action" = 'razorpay_purchase' THEN 'purchase'
    WHEN "action" = 'provision' THEN 'grant'
    WHEN "action" = 'admin_topup' THEN 'adjustment'
    WHEN "amount" < 0 THEN 'consume'
    ELSE 'grant'
  END,
  "actor_type" = COALESCE("actor_type", 'system')
WHERE "kind" IS NULL;
ALTER TABLE "credit_transactions" ALTER COLUMN "kind" SET NOT NULL;
DO $$ BEGIN
  ALTER TABLE "credit_transactions" ADD CONSTRAINT "credit_transactions_kind_check"
    CHECK ("kind" IN ('grant', 'purchase', 'consume', 'refund', 'expire', 'adjustment'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- 3. Opening balance: wallets without a balance row get one equal to their ledger sum; wallets whose
--    balance differs from their ledger sum get one adjustment, so reconciliation starts clean.
INSERT INTO "credit_balances" ("workspace_id", "balance")
SELECT t."workspace_id", GREATEST(SUM(t."amount"), 0)::integer
FROM "credit_transactions" t
WHERE NOT EXISTS (SELECT 1 FROM "credit_balances" b WHERE b."workspace_id" = t."workspace_id")
GROUP BY t."workspace_id"
ON CONFLICT DO NOTHING;

INSERT INTO "credit_transactions" ("workspace_id", "amount", "action", "kind", "reason", "actor_type", "actor_id", "idempotency_key", "balance_after")
SELECT b."workspace_id", b."balance" - COALESCE(s.total, 0), 'opening_balance', 'adjustment',
       'COPS-04 opening balance: ledger brought in line with the stored balance', 'system', 'migration-0112',
       'cops04:opening-balance', b."balance"
FROM "credit_balances" b
LEFT JOIN (SELECT "workspace_id", SUM("amount")::integer AS total FROM "credit_transactions" GROUP BY "workspace_id") s
  ON s."workspace_id" = b."workspace_id"
WHERE b."balance" <> COALESCE(s.total, 0)
  AND NOT EXISTS (
    SELECT 1 FROM "credit_transactions" x
    WHERE x."workspace_id" = b."workspace_id" AND x."idempotency_key" = 'cops04:opening-balance'
  );

-- 4. Append-only: no UPDATE ever; DELETE only when the workspace itself is gone (cascade on delete).
CREATE OR REPLACE FUNCTION "cops_reject_credit_transaction_change"() RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' AND NOT EXISTS (SELECT 1 FROM "workspaces" w WHERE w."id" = OLD."workspace_id") THEN
    RETURN OLD;
  END IF;
  RAISE EXCEPTION 'credit_transactions is append-only; post a compensating entry instead'
    USING ERRCODE = 'P0001', HINT = 'cops_credit_ledger_append_only';
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS "credit_transactions_append_only" ON "credit_transactions";
CREATE TRIGGER "credit_transactions_append_only"
  BEFORE UPDATE OR DELETE ON "credit_transactions"
  FOR EACH ROW EXECUTE FUNCTION "cops_reject_credit_transaction_change"();

-- 5. Reconciliation runs (platform-wide operations table, not tenant data).
CREATE TABLE IF NOT EXISTS "credit_reconciliation_runs" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "started_at" timestamptz NOT NULL DEFAULT now(),
  "finished_at" timestamptz,
  "wallets_checked" integer NOT NULL DEFAULT 0,
  "mismatch_count" integer NOT NULL DEFAULT 0,
  "mismatches" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "triggered_by" text NOT NULL DEFAULT 'schedule'
);
CREATE INDEX IF NOT EXISTS "credit_reconciliation_runs_started_idx" ON "credit_reconciliation_runs" ("started_at" DESC);

-- 6. Provisioning saga, owned by the operator workspace that provisions a customer account.
CREATE TABLE IF NOT EXISTS "cops_provisionings" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,
  "account_id" uuid NOT NULL REFERENCES "companies"("id") ON DELETE CASCADE,
  "opportunity_id" uuid NOT NULL REFERENCES "deals"("id") ON DELETE CASCADE,
  "idempotency_key" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'running', 'succeeded', 'failed')),
  "request" jsonb NOT NULL,
  "provisioned_workspace_id" uuid REFERENCES "workspaces"("id") ON DELETE SET NULL,
  "invite_id" uuid,
  "trial_starts_at" timestamptz,
  "trial_ends_at" timestamptz,
  "requested_by" uuid,
  "last_error" text,
  "attempts" integer NOT NULL DEFAULT 0,
  "started_at" timestamptz,
  "completed_at" timestamptz,
  "duration_ms" integer,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS "cops_provisionings_idempotency_uq" ON "cops_provisionings" ("idempotency_key");
-- At most one successful provisioning per account: a second workspace for the same customer is refused.
CREATE UNIQUE INDEX IF NOT EXISTS "cops_provisionings_one_success_uq"
  ON "cops_provisionings" ("workspace_id", "account_id") WHERE "status" = 'succeeded';
CREATE INDEX IF NOT EXISTS "cops_provisionings_account_idx" ON "cops_provisionings" ("workspace_id", "account_id", "created_at" DESC);

CREATE TABLE IF NOT EXISTS "cops_provisioning_steps" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE CASCADE,
  "provisioning_id" uuid NOT NULL REFERENCES "cops_provisionings"("id") ON DELETE CASCADE,
  "step" text NOT NULL,
  "position" integer NOT NULL,
  "status" text NOT NULL DEFAULT 'pending' CHECK ("status" IN ('pending', 'running', 'succeeded', 'failed')),
  "attempts" integer NOT NULL DEFAULT 0,
  "result" jsonb,
  "error" text,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "duration_ms" integer
);
CREATE UNIQUE INDEX IF NOT EXISTS "cops_provisioning_steps_uq" ON "cops_provisioning_steps" ("provisioning_id", "step");
