/**
 * Test data seed — 15 realistic prospects covering every search filter.
 *
 * Usage (from repo root):
 *   pnpm --filter @skout/api seed:test
 *
 * Or directly:
 *   cd apps/api && pnpm tsx src/seed-test-prospects.ts
 */

import path from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

try {
  const { config } = await import("dotenv");
  config({ path: path.resolve(__dirname, "../../../.env") });
} catch {}

import { createDb, resolveDatabaseUrl } from "@skout/db";
import { prospectActivations } from "@skout/db/schema";
import {
  bulkUpsertProspects,
  ensureProspectsIndex,
  type OpenSearchConfig,
  type ProspectDocument,
} from "@skout/opensearch";

const hash = (v: string) => createHash("sha256").update(v).digest("hex");
const now = new Date().toISOString();
const WORKSPACE_ID = "00000000-0000-4000-8000-000000000001";

// ---------------------------------------------------------------------------
// 15 test prospects — covers every filter field
// ---------------------------------------------------------------------------

const prospects: ProspectDocument[] = [
  {
    prospectId: hash("test-sarah-johnson"),
    companyId: hash("salesforce"),
    fullName: "Sarah Johnson",
    title: "VP of Sales",
    seniority: "vp",
    department: "Sales",
    jobFunction: "AE",
    email: "sarah.johnson@salesforce.com",
    phone: "+1-415-555-0101",
    linkedinUrl: "https://linkedin.com/in/sarah-johnson",
    companyDomain: "salesforce.com",
    companyName: "Salesforce",
    industry: "Software & SaaS",
    subIndustry: "CRM",
    country: "US",
    state: "CA",
    city: "San Francisco",
    employeeCount: 70000,
    companyStage: "public",
    annualRevenue: 31_000_000_000,
    lastFundingRound: "ipo",
    currentlyHiring: true,
    yearsAtCompany: 5,
    yearsInRole: 2,
    techStack: [
      { category: "CRM", technology: "Salesforce" },
      { category: "Analytics", technology: "Tableau" },
    ],
    signals: [
      { type: "recent_hiring", observedAt: now },
      { type: "recently_promoted", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-marcus-chen"),
    companyId: hash("hubspot"),
    fullName: "Marcus Chen",
    title: "Director of Marketing",
    seniority: "director",
    department: "Marketing",
    jobFunction: "Demand Generation",
    email: "marcus.chen@hubspot.com",
    linkedinUrl: "https://linkedin.com/in/marcus-chen",
    companyDomain: "hubspot.com",
    companyName: "HubSpot",
    industry: "Software & SaaS",
    subIndustry: "Marketing Automation",
    country: "US",
    state: "MA",
    city: "Boston",
    employeeCount: 7000,
    companyStage: "public",
    annualRevenue: 2_200_000_000,
    lastFundingRound: "ipo",
    currentlyHiring: true,
    yearsAtCompany: 3,
    yearsInRole: 1,
    techStack: [
      { category: "CRM", technology: "HubSpot" },
      { category: "Cloud", technology: "AWS" },
    ],
    signals: [
      { type: "new_product_launch", observedAt: now },
      { type: "posted_on_linkedin", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-priya-sharma"),
    companyId: hash("stripe"),
    fullName: "Priya Sharma",
    title: "Head of Revenue Operations",
    seniority: "head",
    department: "Operations",
    jobFunction: "RevOps",
    email: "priya.sharma@stripe.com",
    phone: "+1-415-555-0203",
    linkedinUrl: "https://linkedin.com/in/priya-sharma",
    companyDomain: "stripe.com",
    companyName: "Stripe",
    industry: "FinTech",
    subIndustry: "Payments",
    country: "US",
    state: "CA",
    city: "San Francisco",
    employeeCount: 8000,
    companyStage: "series_c_plus",
    annualRevenue: 1_000_000_000,
    lastFundingRound: "series_c",
    totalFunding: 2_200_000_000,
    currentlyHiring: true,
    yearsAtCompany: 4,
    yearsInRole: 2,
    previousCompany: "PayPal",
    techStack: [
      { category: "Payment", technology: "Stripe" },
      { category: "Cloud", technology: "AWS" },
    ],
    signals: [
      { type: "recent_funding", observedAt: now },
      { type: "expansion_new_markets", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-james-wilson"),
    companyId: hash("shopify"),
    fullName: "James Wilson",
    title: "CEO",
    seniority: "ceo",
    department: "Engineering",
    jobFunction: "Growth",
    email: "james.wilson@shopify.com",
    linkedinUrl: "https://linkedin.com/in/james-wilson",
    companyDomain: "shopify.com",
    companyName: "Shopify",
    industry: "Retail & E-Commerce",
    subIndustry: "E-Commerce Platform",
    country: "CA",
    state: "ON",
    city: "Ottawa",
    employeeCount: 12000,
    companyStage: "public",
    annualRevenue: 7_000_000_000,
    lastFundingRound: "ipo",
    currentlyHiring: false,
    yearsAtCompany: 10,
    yearsInRole: 3,
    techStack: [
      { category: "E-Commerce", technology: "Shopify" },
      { category: "Cloud", technology: "GCP" },
    ],
    signals: [
      { type: "new_product_launch", observedAt: now },
      { type: "leadership_change", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-anna-mueller"),
    companyId: hash("sap"),
    fullName: "Anna Mueller",
    title: "C-Level Executive",
    seniority: "c_level",
    department: "Finance",
    jobFunction: "Procurement",
    email: "anna.mueller@sap.com",
    phone: "+49-69-555-0401",
    linkedinUrl: "https://linkedin.com/in/anna-mueller",
    companyDomain: "sap.com",
    companyName: "SAP",
    industry: "Software & SaaS",
    subIndustry: "ERP",
    country: "DE",
    state: "BW",
    city: "Walldorf",
    employeeCount: 100000,
    companyStage: "public",
    annualRevenue: 32_000_000_000,
    lastFundingRound: "ipo",
    currentlyHiring: true,
    yearsAtCompany: 8,
    yearsInRole: 3,
    techStack: [
      { category: "ERP", technology: "SAP" },
      { category: "Analytics", technology: "SAP Analytics Cloud" },
    ],
    signals: [{ type: "recent_hiring", observedAt: now }],
    updatedAt: now,
  },
  {
    prospectId: hash("test-david-kim"),
    companyId: hash("figma"),
    fullName: "David Kim",
    title: "Founder & CTO",
    seniority: "founder",
    department: "Engineering",
    jobFunction: "Growth",
    email: "david.kim@figma.com",
    linkedinUrl: "https://linkedin.com/in/david-kim",
    companyDomain: "figma.com",
    companyName: "Figma",
    industry: "Software & SaaS",
    subIndustry: "Design Tools",
    country: "US",
    state: "CA",
    city: "San Francisco",
    employeeCount: 1200,
    companyStage: "series_c_plus",
    annualRevenue: 400_000_000,
    lastFundingRound: "series_d_plus",
    totalFunding: 333_000_000,
    currentlyHiring: true,
    yearsAtCompany: 7,
    yearsInRole: 7,
    techStack: [
      { category: "Design", technology: "Figma" },
      { category: "Cloud", technology: "AWS" },
    ],
    signals: [
      { type: "recent_funding", observedAt: now },
      { type: "active_on_social_media", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-emily-patel"),
    companyId: hash("notion"),
    fullName: "Emily Patel",
    title: "VP of Product",
    seniority: "vp",
    department: "Product",
    jobFunction: "Product Marketing",
    email: "emily.patel@notion.so",
    phone: "+1-415-555-0601",
    linkedinUrl: "https://linkedin.com/in/emily-patel",
    companyDomain: "notion.so",
    companyName: "Notion",
    industry: "Software & SaaS",
    subIndustry: "Productivity",
    country: "US",
    state: "CA",
    city: "San Francisco",
    employeeCount: 400,
    companyStage: "series_b",
    annualRevenue: 60_000_000,
    lastFundingRound: "series_b",
    totalFunding: 343_000_000,
    currentlyHiring: true,
    yearsAtCompany: 2,
    yearsInRole: 1,
    previousCompany: "Google",
    techStack: [
      { category: "Productivity", technology: "Notion" },
      { category: "Cloud", technology: "AWS" },
    ],
    signals: [
      { type: "recently_promoted", observedAt: now },
      { type: "changed_jobs", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-alex-rodriguez"),
    companyId: hash("intercom"),
    fullName: "Alex Rodriguez",
    title: "Manager, Customer Success",
    seniority: "manager",
    department: "Customer Success",
    jobFunction: "SDR",
    email: "alex.rodriguez@intercom.com",
    linkedinUrl: "https://linkedin.com/in/alex-rodriguez",
    companyDomain: "intercom.com",
    companyName: "Intercom",
    industry: "Software & SaaS",
    subIndustry: "Customer Support",
    country: "US",
    state: "CA",
    city: "San Francisco",
    employeeCount: 900,
    companyStage: "series_c_plus",
    annualRevenue: 200_000_000,
    lastFundingRound: "series_c",
    currentlyHiring: true,
    yearsAtCompany: 3,
    yearsInRole: 1,
    techStack: [
      { category: "CRM", technology: "HubSpot" },
      { category: "Support", technology: "Intercom" },
    ],
    signals: [{ type: "recent_hiring", observedAt: now }],
    updatedAt: now,
  },
  {
    prospectId: hash("test-sophie-martin"),
    companyId: hash("doctolib"),
    fullName: "Sophie Martin",
    title: "Co-Founder",
    seniority: "co_founder",
    department: "Operations",
    jobFunction: "Growth",
    email: "sophie.martin@doctolib.fr",
    phone: "+33-1-555-0801",
    linkedinUrl: "https://linkedin.com/in/sophie-martin",
    companyDomain: "doctolib.fr",
    companyName: "Doctolib",
    industry: "Healthcare",
    subIndustry: "Health Tech",
    country: "FR",
    city: "Paris",
    employeeCount: 2500,
    companyStage: "series_c_plus",
    annualRevenue: 250_000_000,
    lastFundingRound: "series_d_plus",
    totalFunding: 540_000_000,
    currentlyHiring: true,
    yearsAtCompany: 6,
    yearsInRole: 6,
    techStack: [
      { category: "Cloud", technology: "AWS" },
      { category: "Analytics", technology: "Mixpanel" },
    ],
    signals: [
      { type: "expansion_new_markets", observedAt: now },
      { type: "recent_funding", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-ryan-oconnor"),
    companyId: hash("klaviyo"),
    fullName: "Ryan O'Connor",
    title: "Director of Demand Generation",
    seniority: "director",
    department: "Marketing",
    jobFunction: "Demand Generation",
    email: "ryan.oconnor@klaviyo.com",
    linkedinUrl: "https://linkedin.com/in/ryan-oconnor",
    companyDomain: "klaviyo.com",
    companyName: "Klaviyo",
    industry: "Software & SaaS",
    subIndustry: "Marketing Automation",
    country: "US",
    state: "MA",
    city: "Boston",
    employeeCount: 1800,
    companyStage: "public",
    annualRevenue: 698_000_000,
    lastFundingRound: "ipo",
    currentlyHiring: true,
    yearsAtCompany: 2,
    yearsInRole: 2,
    previousCompany: "Mailchimp",
    techStack: [
      { category: "Marketing", technology: "Klaviyo" },
      { category: "E-Commerce", technology: "Shopify" },
    ],
    signals: [
      { type: "posted_on_linkedin", observedAt: now },
      { type: "website_changes", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-nina-berg"),
    companyId: hash("klarna"),
    fullName: "Nina Berg",
    title: "VP Finance",
    seniority: "vp",
    department: "Finance",
    jobFunction: "Procurement",
    email: "nina.berg@klarna.com",
    phone: "+46-8-555-1001",
    linkedinUrl: "https://linkedin.com/in/nina-berg",
    companyDomain: "klarna.com",
    companyName: "Klarna",
    industry: "FinTech",
    subIndustry: "BNPL",
    country: "SE",
    city: "Stockholm",
    employeeCount: 5000,
    companyStage: "series_c_plus",
    annualRevenue: 2_000_000_000,
    lastFundingRound: "series_d_plus",
    totalFunding: 4_500_000_000,
    currentlyHiring: false,
    yearsAtCompany: 4,
    yearsInRole: 2,
    techStack: [
      { category: "Payment", technology: "Stripe" },
      { category: "Cloud", technology: "GCP" },
    ],
    signals: [{ type: "leadership_change", observedAt: now }],
    updatedAt: now,
  },
  {
    prospectId: hash("test-tom-nguyen"),
    companyId: hash("linear"),
    fullName: "Tom Nguyen",
    title: "Software Engineer",
    seniority: "individual_contributor",
    department: "Engineering",
    jobFunction: "SDR",
    email: "tom.nguyen@linear.app",
    linkedinUrl: "https://linkedin.com/in/tom-nguyen",
    companyDomain: "linear.app",
    companyName: "Linear",
    industry: "Software & SaaS",
    subIndustry: "Project Management",
    country: "US",
    state: "CA",
    city: "San Francisco",
    employeeCount: 80,
    companyStage: "series_a",
    annualRevenue: 20_000_000,
    lastFundingRound: "series_a",
    totalFunding: 52_000_000,
    currentlyHiring: true,
    yearsAtCompany: 1,
    yearsInRole: 1,
    techStack: [
      { category: "Project Management", technology: "Linear" },
      { category: "Cloud", technology: "AWS" },
    ],
    signals: [{ type: "active_on_social_media", observedAt: now }],
    updatedAt: now,
  },
  {
    prospectId: hash("test-carlos-silva"),
    companyId: hash("nubank"),
    fullName: "Carlos Silva",
    title: "Head of Growth",
    seniority: "head",
    department: "Marketing",
    jobFunction: "Growth",
    email: "carlos.silva@nubank.com.br",
    phone: "+55-11-555-1201",
    linkedinUrl: "https://linkedin.com/in/carlos-silva",
    companyDomain: "nubank.com.br",
    companyName: "Nubank",
    industry: "FinTech",
    subIndustry: "Digital Banking",
    country: "BR",
    city: "São Paulo",
    employeeCount: 8000,
    companyStage: "public",
    annualRevenue: 1_900_000_000,
    lastFundingRound: "ipo",
    currentlyHiring: true,
    yearsAtCompany: 3,
    yearsInRole: 1,
    previousCompany: "Itaú",
    techStack: [
      { category: "Cloud", technology: "AWS" },
      { category: "Analytics", technology: "Amplitude" },
    ],
    signals: [
      { type: "expansion_new_markets", observedAt: now },
      { type: "changed_jobs", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-jessica-lee"),
    companyId: hash("zendesk"),
    fullName: "Jessica Lee",
    title: "Senior Manager, Recruiting",
    seniority: "manager",
    department: "HR",
    jobFunction: "Recruiting",
    email: "jessica.lee@zendesk.com",
    linkedinUrl: "https://linkedin.com/in/jessica-lee",
    companyDomain: "zendesk.com",
    companyName: "Zendesk",
    industry: "Software & SaaS",
    subIndustry: "Customer Support",
    country: "US",
    state: "CA",
    city: "San Francisco",
    employeeCount: 6500,
    companyStage: "public",
    annualRevenue: 1_700_000_000,
    lastFundingRound: "ipo",
    currentlyHiring: true,
    yearsAtCompany: 5,
    yearsInRole: 2,
    techStack: [
      { category: "Support", technology: "Zendesk" },
      { category: "CRM", technology: "Salesforce" },
    ],
    signals: [
      { type: "recent_hiring", observedAt: now },
      { type: "website_changes", observedAt: now },
    ],
    updatedAt: now,
  },
  {
    prospectId: hash("test-oliver-schmidt"),
    companyId: hash("personio"),
    fullName: "Oliver Schmidt",
    title: "Founder & CEO",
    seniority: "founder",
    department: "Operations",
    jobFunction: "Growth",
    email: "oliver.schmidt@personio.de",
    phone: "+49-89-555-1401",
    linkedinUrl: "https://linkedin.com/in/oliver-schmidt",
    companyDomain: "personio.de",
    companyName: "Personio",
    industry: "Software & SaaS",
    subIndustry: "HR Software",
    country: "DE",
    state: "BY",
    city: "Munich",
    employeeCount: 1800,
    companyStage: "series_c_plus",
    annualRevenue: 200_000_000,
    lastFundingRound: "series_d_plus",
    totalFunding: 724_000_000,
    currentlyHiring: true,
    yearsAtCompany: 8,
    yearsInRole: 8,
    techStack: [
      { category: "HR", technology: "Personio" },
      { category: "Cloud", technology: "AWS" },
    ],
    signals: [
      { type: "recent_funding", observedAt: now },
      { type: "expansion_new_markets", observedAt: now },
      { type: "new_product_launch", observedAt: now },
    ],
    updatedAt: now,
  },
];

// ---------------------------------------------------------------------------
// Insert into PostgreSQL
// ---------------------------------------------------------------------------

const databaseUrl = resolveDatabaseUrl();
const { db, sql } = createDb(databaseUrl);

console.log(`\nSeeding ${prospects.length} prospects into PostgreSQL...`);

for (const p of prospects) {
  await db
    .insert(prospectActivations)
    .values({
      workspaceId: WORKSPACE_ID,
      prospectId: p.prospectId,
      companyId: p.companyId,
      snapshot: {
        prospectId: p.prospectId,
        companyId: p.companyId,
        fullName: p.fullName,
        title: p.title,
        seniority: p.seniority,
        industry: p.industry,
        country: p.country,
        companyDomain: p.companyDomain,
        companyName: p.companyName,
        email: p.email,
        employeeCount: p.employeeCount,
      },
    })
    .onConflictDoNothing();

  console.log(`  ✓ ${p.fullName} — ${p.title} @ ${p.companyName}`);
}

await sql.end();
console.log("PostgreSQL done.\n");

// ---------------------------------------------------------------------------
// Upsert into OpenSearch
// ---------------------------------------------------------------------------

const osUrl = process.env.OPENSEARCH_URL;

if (!osUrl) {
  console.log("OPENSEARCH_URL not set — skipping OpenSearch. Set it in .env to enable search.");
} else {
  const cfg: OpenSearchConfig = {
    url: osUrl,
    username: process.env.OPENSEARCH_USERNAME,
    password: process.env.OPENSEARCH_PASSWORD,
    index: process.env.OPENSEARCH_INDEX ?? "prospects",
  };
  console.log(`Upserting into OpenSearch index "${cfg.index}"...`);
  await ensureProspectsIndex(cfg);
  const { ingested, failed } = await bulkUpsertProspects(cfg, prospects);
  console.log(`OpenSearch — ingested: ${ingested}, failed: ${failed}`);
}

console.log("\nSeed complete.");
